import './models/song_album.dart';
import './models/album.dart';

// Top albums streamed on spotify
const Dummy_Data_Albums = [
  Album(
    rank: "1",
    name: "÷ (Deluxe)",
    artistName: "Ed Sheeran",
    imageUrl: "assets/divide.jpg",
  ),
  Album(
    rank: "2",
    name: "beerbongs & bentleys",
    artistName: "Post Malone",
    imageUrl: "assets/beerbongs_&_bentleys.jpg",
  ),
  Album(
    rank: "3",
    name: "Dua Lipa (Complete Edition)",
    artistName: "Dua Lipa",
    imageUrl: "assets/dua_lipa.jpg",
  ),
  Album(
    rank: "4",
    name: "Hollywood's Bleeding",
    artistName: "Post Malone",
    imageUrl: "assets/Hollywoods_Bleeding.jpg",
  ),
  Album(
    rank: "5",
    name: "x (Wembley Edition)",
    artistName: "Ed Sheeran",
    imageUrl: "assets/multiply.jpg",
  ),
  Album(
    rank: "6",
    name: "Future Nostalgia (The Moonlight Edition)",
    artistName: "Dua Lipa",
    imageUrl: "assets/future_nostalgia.jpg",
  ),
  Album(
    rank: "7",
    name: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    artistName: "Billie Eilish",
    imageUrl: "assets/Where_do_we_go_when_we_fall_asleep.jpg",
  ),
  Album(
    rank: "8",
    name: "? (Deluxe)",
    artistName: "XXXTENTACION",
    imageUrl: "assets/quesiton.jpg",
  ),
  Album(
    rank: "9",
    name: "Purpose (Deluxe)",
    artistName: "Justin Bieber",
    imageUrl: "assets/purpose.jpg",
  ),
  Album(
    rank: "10",
    name: "Scorpion",
    artistName: "Drake",
    imageUrl: "assets/scorpion.jpg",
  )
];
const Dummty_Album_songs = [
  SongAlbum(
    rank: '1',
    id: '1',
    name: 'Eraser',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '2',
    name: 'Castle on the Hill',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '3',
    name: 'Dive',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '4',
    name: 'Shape of You',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '5',
    name: 'Perfect',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '6',
    name: 'Galway Girl',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '7',
    name: 'Happier',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '8',
    name: "Hearts Don't Break Around Here",
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '9',
    name: 'New Man',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '10',
    name: 'What Do I Know?',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '11',
    name: 'How Would You Feel (Paean)',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '12',
    name: 'Supermarket Flowers',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '13',
    name: 'Barcelona',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '14',
    name: 'Bibia Be Ye Ye',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '15',
    name: 'Nancy Mulligan',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '1',
    id: '16',
    name: 'Save Myself',
    Album: '÷ (Deluxe)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/divide.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '1',
    name: 'Paranoid',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '2',
    name: 'Spoil My Night',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '3',
    name: 'Rich & Sad',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '4',
    name: 'Zack and Codeine',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '5',
    name: "Takin' Shots",
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '6',
    name: 'rockstar',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '7',
    name: 'Over Now',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '8',
    name: 'Psycho',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '9',
    name: 'Better Now',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '10',
    name: 'Ball For Me',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '11',
    name: 'Otherside',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '12',
    name: 'Stay',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '13',
    name: 'Blame It On Me',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '14',
    name: 'Same Bitches',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '15',
    name: 'Jonestown',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '16',
    name: '92 Explorer',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '17',
    name: 'Candy Paint',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '2',
    id: '18',
    name: 'Sugar Wraith',
    Album: 'beerbongs & bentleys',
    Artist: 'Post Malone',
    imageUrl: 'assets/beerbongs_&_bentleys.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '1',
    name: 'Genesis',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '2',
    name: 'Lost In Your Light',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '3',
    name: 'Hotter Than Hell',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '4',
    name: 'Be The One',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '5',
    name: 'IDGAF',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '6',
    name: 'Blow Your Mind',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '7',
    name: 'Garden',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '8',
    name: 'No Goodbyes',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '9',
    name: "Thinking 'Bout You",
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '10',
    name: 'New Rules',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '11',
    name: 'Begging',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '3',
    id: '12',
    name: 'Homesick',
    Album: 'Dua Lipa (Complete Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/dua_lipa.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '1',
    name: "Hollywood's Bleeding",
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '2',
    name: 'Saint-Tropez',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '3',
    name: 'Enemies',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '4',
    name: 'Allergic',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '5',
    name: 'A Thousand Bad Times',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '6',
    name: 'Circles',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '7',
    name: 'Die For Me',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywood\'s_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '8',
    name: 'On The Road',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywood\'s_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '9',
    name: 'Take What You Want',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywood\'s_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '10',
    name: "I'm Gonna Be",
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '11',
    name: 'Staring At The Sun',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '12',
    name: 'Sunflower (Spider-Man: Into The Spider-Verse)',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '13',
    name: 'Internet',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '14',
    name: 'Goodbyes',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '15',
    name: 'Myself',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '16',
    name: 'I Know',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '4',
    id: '17',
    name: 'Wow.',
    Album: "Hollywood's Bleeding",
    Artist: 'Post Malone',
    imageUrl: 'assets/Hollywoods_Bleeding.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '1',
    name: 'One',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '2',
    name: 'Mess',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '3',
    name: 'Sing',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '4',
    name: "Don't",
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '5',
    name: 'Nina',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '6',
    name: 'Photograph',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '7',
    name: 'Bloodstream',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '8',
    name: 'Tenerife',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '9',
    name: 'Runaway',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '10',
    name: 'The Man',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '11',
    name: 'Thinking Out Loud',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '12',
    name: 'Afire Love',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '13',
    name: 'Take It Back',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '14',
    name: 'Even My Dad Does Sometimes',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '15',
    name: 'Shirtsleeves',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '5',
    id: '15',
    name: 'I See Fire',
    Album: 'x (Wembley Edition)',
    Artist: 'Ed Sheeran',
    imageUrl: 'assets/multiply.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '1',
    name: 'Future Nostalgia',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '2',
    name: "Don't Start Now",
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '3',
    name: 'Cool',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '4',
    name: 'Physical',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '5',
    name: 'Levitating',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '6',
    name: 'Pretty Please',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '7',
    name: 'Hallucinate',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '8',
    name: 'Love Again',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '9',
    name: 'Break My Heart',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '10',
    name: 'Good In Bed',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '6',
    id: '11',
    name: 'Boys Will Be Boys',
    Album: 'Future Nostalgia (The Moonlight Edition)',
    Artist: 'Dua Lipa',
    imageUrl: 'assets/future_nostalgia.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '1',
    name: 'Bad Guy',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '2',
    name: 'Xanny',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '3',
    name: 'You Should See Me In A Crown',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '4',
    name: 'All The Good Girls Go To Hell',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '5',
    name: 'Wish You Were Gay',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '6',
    name: "When The Party's Over",
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '7',
    name: '8',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '8',
    name: 'My Strange Addiction',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '9',
    name: 'Bury A Friend',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '10',
    name: 'Ilomilo',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '11',
    name: 'Listen Before I Go',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '12',
    name: 'I Love You',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '7',
    id: '13',
    name: 'Goodbye',
    Album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    Artist: 'Billie Eilish',
    imageUrl: 'assets/Where_do_we_go_when_we_fall_asleep.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '1',
    name: 'Introduction',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '2',
    name: 'Alone, Part 3',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '3',
    name: 'Moonlight',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '4',
    name: 'Sad!',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '5',
    name: 'The Remedy For A Broken Heart',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '6',
    name: 'Floor 555',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '7',
    name: 'Numb',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '8',
    name: 'Infinity (888)',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '9',
    name: 'Going Down!',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '10',
    name: 'Pain = Bestfriend',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '11',
    name: 'Love Yourself (Interlude)',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '12',
    name: 'Smash!',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '13',
    name: "I Don't Even Speak Spanish Lol",
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '14',
    name: 'Changes',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '15',
    name: 'Hope',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '16',
    name: 'Schizophrenia',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '8',
    id: '17',
    name: 'Before I Close My Eyes',
    Album: '? (Deluxe)',
    Artist: 'XXXTENTACION',
    imageUrl: 'assets/quesiton.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '1',
    name: 'Mark My Words',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '2',
    name: "I'll Show You",
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '3',
    name: 'What Do You Mean?',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '4',
    name: 'Sorry',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '5',
    name: 'Love Yourself',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '6',
    name: 'Company',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '7',
    name: 'No Pressure',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '8',
    name: 'No Sense',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '9',
    name: 'The Feeling',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '10',
    name: 'Life Is Worth Living',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '11',
    name: 'Where Are Ü Now',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '12',
    name: 'Children',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '13',
    name: 'Purpose',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '14',
    name: 'Been You',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '15',
    name: 'Get Used To Me',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '16',
    name: 'We Are',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '17',
    name: 'Trust',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '9',
    id: '18',
    name: 'All In It',
    Album: 'Purpose (Deluxe)',
    Artist: 'Justin Bieber',
    imageUrl: 'assets/purpose.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '1',
    name: 'Survival',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '2',
    name: 'Nonstop',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '3',
    name: 'Elevate',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '4',
    name: 'Emotionless',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '5',
    name: "God's Plan",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '6',
    name: "I'm Upset",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '7',
    name: '8 Out Of 10',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '8',
    name: 'Mob Ties',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '9',
    name: "Can't Take A Joke",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '10',
    name: "Sandra's Rose",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '11',
    name: 'Talk Up',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '12',
    name: 'Is There More',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '13',
    name: 'Peak',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '14',
    name: 'Summer Games',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '15',
    name: 'Jaded',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '16',
    name: 'Nice For What',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '17',
    name: 'Finesse',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '18',
    name: 'Ratchet Happy Birthday',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '19',
    name: "That's How You Feel",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '20',
    name: 'Blue Tint',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '21',
    name: 'In My Feelings	',
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '22',
    name: "Don't Matter To Me",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '23',
    name: "After Dark",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '24',
    name: "Final Fantasy",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  ),
  SongAlbum(
    rank: '10',
    id: '25',
    name: "March 14",
    Album: 'Scorpion',
    Artist: 'Drake',
    imageUrl: 'assets/scorpion.jpg',
  )
];
